base_path: obsidion
base_url: "https://api.crowdin.com"
preserve_hierarchy: true
files:
  - source: core/**/messages.pot
    translation: /%original_path%/%locale%.po
  - source: cogs/**/messages.pot
    translation: /%original_path%/%locale%.po
