version: "3.7"
services:
  bot:
    volumes:
      - ./obsidion:/app/obsidion
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=hunter12
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
